# @package _global_
launcher: torchrun
models:
  XDG_CACHE_HOME: ~/.cache


hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - misc.global_seed
          - presets
    env_set:
      OMP_NUM_THREADS: 40
      TORCHINDUCTOR_CACHE_DIR: ~/.cache/torchinductor_cache

dataset:
  shards: ${oc.env:PWD}/../webvid/webvid_desc.json

training:
  batch_size: 2

misc:
  checkpointing: True
  gradient_accumulation_steps: 4
  vae_chunk_size: 32
  flow_chunk_size: 32

logging_args:
  wandb:
    group: "custom_cluster"

validation:
  first: true
  every_steps: 20
  batch_size: 2